### ISSUE TITLE
ParameterNotFoundException

### ISSUE THREAD

**Issue by adrienthiery** [jjanvier/CrowdinBundle#6]
Hi there, 

I was trying to install your bundle (seems great), but when I do my composer require, I had several issues.

First I got : 
```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]                
  Unrecognized options "crowdin_api_key, crowdin_project_identifier" under "jjanvier_crowdin"  
```

I had to modify the config.yml file for : 
```
jjanvier_crowdin:
    crowdin:
        api_key: %crowdin_api_key%
        project_identifier: %crowdin_project_identifier%
```
instead of the README.md proposed : 
```
jjanvier_crowdin:
        crowdin_api_key: %crowdin_api_key%
        crowdin_project_identifier: %crowdin_project_identifier%
```

Now it works, I get a new error : 
```
[Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]                                                                                                                                                                   
  The service "jjanvier_crowdin.synchronizer.git_handler" has a dependency on a non-existent parameter "jjanvier_crowdin.github.username". Did you mean one of these: "jjanvier_crowdin.github.pr_title", "jjanvier_crowdin.github.pr_message"?  
```

If I start to put my username adding to the config like hereafter, I need to put my email, and then a token. Isn't composer supposed to ask for me to login instead ? 
```
jjanvier_crowdin:
    crowdin:
        api_key: %crowdin_api_key%
        project_identifier: %crowdin_project_identifier%
    github:
        username: <username>
        email: <email>
        token: <????>
```

Any idea why it doesn't? Or what I should do to make it work?
If it is not supposed to ask for a login, what am I supposed to put in the token ?

Thanks in advance.
